from enum import StrEnum


class AnalysisStatus(StrEnum):
    CREATED = "CREATED"
    INGESTED = "INGESTED"
    PARSED = "PARSED"
    EXTRACTED = "EXTRACTED"
    NORMALIZED = "NORMALIZED"
    MODELED = "MODELED"
    RECONCILED = "RECONCILED"
    FINDINGS_GENERATED = "FINDINGS_GENERATED"
    FAILED = "FAILED"
    RETRY = "RETRY"
    DEAD = "DEAD"


class DocumentType(StrEnum):
    CONTRACT = "CONTRACT"
    AMENDMENT = "AMENDMENT"
    INVOICE = "INVOICE"
    DELIVERY_RECORD = "DELIVERY_RECORD"
    OTHER = "OTHER"


class Unit(StrEnum):
    HOUR = "HOUR"
    UNIT = "UNIT"
    DAY = "DAY"
    FIXED = "FIXED"


class Currency(StrEnum):
    USD = "USD"
    EUR = "EUR"
    GBP = "GBP"
    PKR = "PKR"


class ReconciliationStatus(StrEnum):
    NO_FINDING = "NO_FINDING"
    POTENTIAL_BREAK = "POTENTIAL_BREAK"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    RATE_MISMATCH = "RATE_MISMATCH"
    QUANTITY_MISMATCH = "QUANTITY_MISMATCH"
    CHANGE_VALUE_NOT_CAPTURED = "CHANGE_VALUE_NOT_CAPTURED"
    DELIVERED_VALUE_NOT_CAPTURED = "DELIVERED_VALUE_NOT_CAPTURED"
    CURRENCY_CONFLICT = "CURRENCY_CONFLICT"
    DUPLICATE = "DUPLICATE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class FindingStatus(StrEnum):
    POTENTIAL = "POTENTIAL"
    VERIFIED = "VERIFIED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
