from enum import StrEnum


class ErrorCode(StrEnum):
    UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    PARSE_FAILED = "PARSE_FAILED"
    EXTRACTION_SCHEMA_INVALID = "EXTRACTION_SCHEMA_INVALID"
    SOURCE_MISSING = "SOURCE_MISSING"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    CURRENCY_CONFLICT = "CURRENCY_CONFLICT"
    DUPLICATE_ECONOMIC_EVENT = "DUPLICATE_ECONOMIC_EVENT"
    INTERNAL_ERROR = "INTERNAL_ERROR"
